### ISSUE TITLE
Impossible d'aller sur le site

### ISSUE THREAD

**Issue by Olyno** [noftaly/metea#1]
Comme je l'ai signalé sur le discord, le site est **inaccessible** car l’adresse du lien pour accéder au site est ``localhost:3000`` et nous ne pouvons pas accéder à une adresse locale, car comme son nom l'indique, elle est locale.

**Comment by noftaly** [comment]
Je sais, mais c'est parce que je ne l'ai pas hébergé ! Si tu veux l'héberger, pas de problème 😅 mais c'est généralement payant...
En attendant je l'ai mis ici : https://noftaly-metealy.glitch.me , mais c'est pas optimal, donc je n'ai pas encore changé les liens. Je les changerai quand l'hébergeur sera définitif.

**Comment by Olyno** [comment]
Tu as Heroku comme bon hebergeur gratuit
